<?php $_helper = $this->helper('Smartwave\Porto\Helper\Data');?>
<div class="container">
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <?php echo $this->getChildHtml("logo"); ?>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <div class="nav-link"><?php echo $this->getChildHtml("top.search"); ?></div>
          </li>
          <li class="nav-item">
            <div class="nav-link"><?php echo $this->getChildHtml("custom_block"); ?></div>
          </li>
          <li class="nav-item">
            <a href="<?php echo $_helper->getBaseLinkUrl().'customer/account/' ?>" class="nav-link" title="My Account"><i class="porto-icon-user-2"></i></a>
          </li>
          <li class="nav-item">
            <div class="nav-link"><?php echo $this->getChildHtml("minicart"); ?></div>
          </li>
          <li class="nav-item">
            <div class="nav-link">
                <input type="text" name="delivery_location" placeholder="Enter you location">
            </div>
          </li>
        </ul>        
      </div>
    </div>
  </nav>
</div>
<?php echo $this->getChildHtml("navigation.sections"); ?>