<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>
<?php $stockItem = $_product->getExtensionAttributes()->getStockItem() ?>
<?php $qty = $stockItem->getQty() ?>
<?php $stockStatus = $stockItem->getIsInStock() ?>
<?php if ($block->displayProductStockStatus()): ?>
    <div class="stock available" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
        <span class="label"><?php /* @escapeNotVerified */ echo __('Availability:') ?></span>
        <span><?php /* @escapeNotVerified */ echo $stockStatus ?></span>
    </div>
<?php endif; ?>
