<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>
<?php $stockItem = $_product->getExtensionAttributes()->getStockItem() ?>
<?php $qty = $stockItem->getQty() ?>
<?php $stockStatus = $stockItem->getIsInStock() ?>
<?php $availabilityStatus = $_product->getAttributeText('stock_availability_status') ?>
<?php if ($block->displayProductStockStatus()): ?>
    <?php if($qty > 0 && $stockStatus == 1 && !in_array($availabilityStatus, ["Call to Order","Out of Stock","**Special Order**","**Clearance**"],true)): ?>
        <div class="stock available" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
            <span class="label"><?php /* @escapeNotVerified */ echo __('Availability:') ?></span>
            <span><?php /* @escapeNotVerified */ echo __('In Stock') ?></span>
        </div>
    <?php else:?>
        <div class="stock available" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
            <span class="label"><?php /* @escapeNotVerified */ echo __('Availability:') ?></span>
            <span><?php /* @escapeNotVerified */ echo __('Available') ?></span>
        </div>
    <?php endif;?>
<?php endif; ?>
