<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Catalog\ViewModel\Product\Listing\PreparePostData;
use Magento\Framework\App\ActionInterface;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Generic.WhiteSpace.ScopeIndent.Incorrect

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>
<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'product_base_image';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'product_base_image';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'product_base_image';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'product_base_image';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'product_base_image';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'product_base_image';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'product_base_image';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    default:
        $exist = null;
}
$_item = null;
?>

<?php if ($exist) : ?>

    <?php if ($type == 'related' || $type == 'upsell') : ?>
        <?php if ($type == 'related') : ?>
            <div class="block <?= $block->escapeHtmlAttr($class) ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?= $block->escapeHtmlAttr($limit) ?>" data-shuffle="<?= /* @noEscape */ $shuffle ?>">
            <?php else : ?>
                <div class="block <?= $block->escapeHtmlAttr($class) ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?= $block->escapeHtmlAttr($limit) ?>" data-shuffle="<?= /* @noEscape */ $shuffle ?>">
                <?php endif; ?>
            <?php else : ?>
                <div class="block <?= $block->escapeHtmlAttr($class) ?>">
                <?php endif; ?>
                <div class="block-title title">
                    <strong id="block-<?= $block->escapeHtmlAttr($class) ?>-heading" role="heading" aria-level="2">Other items you might need</strong>
                </div>
                <div class="block-content content" aria-labelledby="block-<?= $block->escapeHtmlAttr($class) ?>-heading">
                    <div class="products wrapper grid products-grid products-<?= $block->escapeHtmlAttr($type) ?>">
                        <div class="row products list items product-items">
                            <?php foreach ($items as $_item) : ?>
                                <?php $available = ''; ?>
                                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related') : ?>
                                    <?php if (!$_item->getRequiredOptions()) : ?>
                                        <?php $available = 'related-available'; ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($type == 'related' || $type == 'upsell') : ?>
                                    <div class="col-lg-3 item product product-item rel-products" style="display: none;">
                                    <?php else : ?>
                                        <div class="col-lg-3 item product product-item rel-products">
                                        <?php endif; ?>
                                        <div class="product-item-info <?= /* @noEscape */ $available ?>">
                                            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
                                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product photo product-item-photo">
                                                <?= $block->getImage($_item, $image)->toHtml() ?>
                                            </a>
                                            <div class="product details product-item-details">
                                                <strong class="product name product-item-name"><a class="product-item-link" title="<?= $block->escapeHtmlAttr($_item->getName()) ?>" href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                                        <?= $block->escapeHtml($_item->getName()) ?></a>
                                                </strong>

                                                <?= /* @noEscape */ $block->getProductPrice($_item) ?>

                                                <?php if ($templateType) : ?>
                                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                                <?php endif; ?>


                                                <?php // phpcs:disable 
                                                ?>
                                                <div class="product actions product-item-actions" style="margin: unset !important;">

                                                    <?php if ($_item->isSaleable()) : ?>
                                                        <div class="actions-primary">
                                                            <?php
                                                            /** @var $viewModel PreparePostData */
                                                            $viewModel = $block->getViewModel();
                                                            $postArray = $viewModel->getPostData(
                                                                $block->escapeUrl($block->getAddToCartUrl($_item)),
                                                                ['product' => $_item->getEntityId()]
                                                            );
                                                            $value = $postArray['data'][ActionInterface::PARAM_NAME_URL_ENCODED];
                                                            ?>
                                                            <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>" action="<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>" method="post">
                                                                <input type="hidden" name="product" value="<?= /* @noEscape */ (int)$_item->getEntityId() ?>">
                                                                <input type="hidden" name="<?= /* @noEscape */ ActionInterface::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $value ?>">
                                                                <?= $block->getBlockHtml('formkey') ?>

                                                                <?php if ($_item->getAttributeText('stock_availability_status') == 'Call to Order') : ?>
                                                                    <a role="button" href="<?= $_item->getProductUrl(); ?>" class="action tocart primary">
                                                                        <span>Call To Order</span>
                                                                    </a>
                                                                <?php else : ?>
                                                                    <button type="submit" title="<?php echo $block->escapeHtml(__('Add To Cart')); ?>" class="action tocart primary">
                                                                        <span><?php echo __('Add To Cart') ?></span>
                                                                    </button>
                                                                <?php endif; ?>
                                                            </form>


                                                        <?php else : ?>
                                                            <?php if ($_item->getIsSalable()) : ?>
                                                                <div class="stock available">
                                                                    <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                                </div>
                                                            <?php else : ?>
                                                                <div class="stock unavailable">
                                                                    <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                                </div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                        </div>
                                                </div>
                                                <?php // phpcs:enable 
                                                ?>

                                            </div>
                                        </div>
                                        </div>
                                    <?php endforeach ?>
                                    </div>
                        </div>
                    </div>
                </div>
                <?php if (!$block->isRedirectToCartEnabled() && $_item) : ?>
                    <script type="text/x-magento-init">
                        {
                "[data-role=tocart-form], .form.map.checkout": {
                    "catalogAddToCart": {
                        "product_sku": "<?= $block->escapeJs($_item->getSku()) ?>"
                    }
                }
            }
            </script>
                <?php endif; ?>
            <?php endif; ?>

            